# Generated by Django 2.2.1 on 2019-05-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('departament', models.TextField()),
                ('createdAt', models.DateField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
